name: $(Date:yyyyMMdd)$(Rev:.r)-Infrastructure
trigger: none
pr: none

# Pool Configuration
pool:
  name: 'Self hosted pools'
  demands:
    - Agent.Name -equals alaaynassar-VMware

parameters:
  - name: env
    displayName: Environment
    type: string
    default: nonprod
    values: [nonprod, prod]

  - name: action
    displayName: Action
    type: string
    default: apply
    values: [plan, apply, destroy]

variables:
  TF_DIR: 'terraform'
  TF_VAR_FILE: '${{ parameters.env }}.tfvars'
  AWS_SERVICE_CONNECTION: 'aws-alaa-2'
  AWS_REGION: 'us-east-2'

jobs:
- job: Infrastructure
  displayName: 'Infrastructure Provisioning'
  timeoutInMinutes: 120
  steps:
  - checkout: self

  - task: TerraformInstaller@1
    displayName: Install Terraform
    inputs:
      terraformVersion: latest

  - task: AWSShellScript@1
    displayName: Terraform Init
    inputs:
      awsCredentials: $(AWS_SERVICE_CONNECTION)
      regionName: $(AWS_REGION)
      scriptType: inline
      inlineScript: |
        set -euo pipefail
        cd "$(TF_DIR)"
        terraform init

  - task: AWSShellScript@1
    displayName: Terraform Execution
    inputs:
      awsCredentials: $(AWS_SERVICE_CONNECTION)
      regionName: $(AWS_REGION)
      scriptType: inline
      inlineScript: |
        set -euo pipefail
        cd "$(TF_DIR)"
        
        ACTION="${{ parameters.action }}"
        echo "Selected Action: $ACTION"

        if [ "$ACTION" = "destroy" ]; then
          echo "Running Pre-Destroy Cleanup (AWS CLI Method)..."
          
          # 1. Get VPC ID from Terraform
          if ! VPC_ID=$(terraform output -raw vpc_id 2>/dev/null); then
             echo "Could not fetch VPC ID from state. Skipping LB cleanup."
          else
             echo "Target VPC ID: $VPC_ID"
             
             # 2. Delete Classic ELBs in VPC
             echo "Checking for Classic ELBs..."
             ELB_NAMES=$(aws elb describe-load-balancers --region $(AWS_REGION) --query "LoadBalancerDescriptions[?VPCId=='$VPC_ID'].LoadBalancerName" --output text)
             if [ -n "$ELB_NAMES" ]; then
               for elb in $ELB_NAMES; do
                 echo "Deleting Classic ELB: $elb"
                 aws elb delete-load-balancer --region $(AWS_REGION) --load-balancer-name "$elb"
               done
             else
               echo "No Classic ELBs found."
             fi

             # 3. Delete ELBv2 (ALB/NLB) in VPC
             echo "Checking for V2 Load Balancers (ALB/NLB)..."
             ELB_ARNS=$(aws elbv2 describe-load-balancers --region $(AWS_REGION) --query "LoadBalancers[?VpcId=='$VPC_ID'].LoadBalancerArn" --output text)
             if [ -n "$ELB_ARNS" ]; then
               for arn in $ELB_ARNS; do
                 echo "Deleting ELBv2: $arn"
                 aws elbv2 delete-load-balancer --region $(AWS_REGION) --load-balancer-arn "$arn"
               done
               
               echo "Waiting for ELBv2 deletion..."
               sleep 15
             else
               echo "No V2 Load Balancers found."
             fi
             
             echo "Waiting 30 seconds for AWS cleanup..."
             sleep 30
          fi

          echo "Running Terraform Destroy..."
          terraform destroy -auto-approve -var-file="$(TF_VAR_FILE)" -lock=false
          exit 0
        
        elif [ "$ACTION" = "plan" ]; then
          echo "Running Terraform Plan..."
          terraform plan -var-file="$(TF_VAR_FILE)"
        
        elif [ "$ACTION" = "apply" ]; then
          echo "Running Terraform Apply..."
          terraform apply -auto-approve -var-file="$(TF_VAR_FILE)"
        
        else
          echo "Invalid action specified."
          exit 1
        fi