name: $(Date:yyyyMMdd)$(Rev:.r)-Release
trigger: none
pr: none

variables:
  AWS_SERVICE_CONNECTION: 'alaa-s'
  AWS_REGION: 'us-east-1'
  IMAGE_REPOSITORY: 'alaaynassar7/motivational-app'

pool:
  name: 'Self hosted pools'
  demands:
    - Agent.Name -equals alaaynassar-VMware

jobs:
- job: Release
  displayName: 'Build and Release Docker Image'
  steps:
  - checkout: self

  # Build and Push using the correct sub-directory path from your GitHub images
  - task: Docker@2
    displayName: Build and Push Docker Image
    inputs:
      containerRegistry: 'alaa-docker'
      repository: $(IMAGE_REPOSITORY)
      command: 'buildAndPush'
      # Path updated based on your 'motivational-app' folder structure
      Dockerfile: 'motivational-app/dockerfile' 
      # buildContext is essential so Docker sees app.py and requirements.txt
      buildContext: 'motivational-app'
      tags: |
        $(Build.BuildId)
        latest